### ISSUE TITLE
Missing checks after mutex-unlock! in presence of a condition-variable

### ISSUE THREAD

**Issue by kdltr** [Adellica/chicken-gochan#3]
Hi, I just found an annoying bug.

When signals are involved, gochan crashes my program with an “assertion failed” message.

```
Error: (gochan.scm:502) assertion failed: (gosem-meta semaphore)

        Call history:

        gochan.scm:488: gosem-mutex
        gochan.scm:489: gosem-cv
        gochan.scm:488: mutex-unlock!
        gochan.scm:499: g1321
        gochan.scm:347: gochan-mutex
        gochan.scm:347: mutex-lock!
        gochan.scm:348: info
        gochan.scm:349: gochan-receivers
        gochan.scm:349: %remove-queue-item
        gochan.scm:332: queue-length
        gochan.scm:334: queue-remove!
        gochan.scm:337: loop
        gochan.scm:350: gochan-mutex
        gochan.scm:350: mutex-unlock!
        gochan.scm:502: gosem-meta
        gochan.scm:502: ##sys#error             <--


```

This is due to the code not checking the state of the semaphore objects after a `mutex-unlock!` with a condition-variable. These `mutex-unlock!` calls might be interrupted before the condition variable is signaled, for example when a signal handler is run.

Here is a patch that fixes this behaviour. Make sure it’s ok, I’m not used to the gochan codebase. :)

**Comment by kdltr** [comment]
Here’s the patch

#4

**Comment by kristianlm** [comment]
#4 is merged and tests pass, thanks for your help!
