### ISSUE TITLE
How to do prioritize select?

### ISSUE THREAD

**Issue by siiky** [Adellica/chicken-gochan#7]
Hi again :)

I'm trying to use CHICKEN exclusively for a course I'm enrolled in, which is proving to be very interesting and rewarding, but also challenging. In this course we're using [Maelstrom](https://github.com/jepsen-io/maelstrom) to implement and experiment with distributed algorithms and distributed programming, and I hit a limitation with my previous "recipe", in that I have no easy way of implementing timeouts, heartbeats, and the like. Because of that I'm turning now to `gochan` which is more at-home for me (having a bit of experience with Erlang and Go).

However, I have a problem: let's say I have two channels `Ci` and `Ct` (for input and timeout), and that the main thread does a `gochan-select` on both of them. Would it be possible to somehow prioritize one of the channels over the other (`Ct` over `Ci`, specifically)?

Without the "shuffle" mentioned in #6 it's obvious to me how: just order the `Ct` before the `Ci`. (In the meantime I'll remove the shuffle from `gochan-select*`)

**Comment by kristianlm** [comment]
Hi siiky,
Thanks for giving gochan a try.

I'm afraid there are no mechanisms for priority in place. Like you discovered, `shuffle` is hardcoded in.

You can however cheat i bit in some cases, like this:

```scheme
(gochan-select
  ((pri1 -> msg fail) ...)
  (else 
    (gochan-select
        ((pri1 -> msg fail) ...)
        ((pri2 -> msg fail) ...))))
```

Where the two bodies of pri1 should be identical. That ensures handling of channel pri1 before pri2 at the start of that snippet.

**Comment by siiky** [comment]
Oh of course! I forgot about that trick! Thanks
